In [1]:
import numpy as np

def dist(x,y):
  return sum([abs(x[i]-y[i]) for i in range(len(x))])

def jacobi( A , b , max_iter=1000 , x0 = None , tol = 1.0e-5):
  '''Método de Jacobi no sistema Ax=b'''

  n = len(A)
  if (x0 == None):
    x0 = [0]*n

  x_new = x0.copy()

  err = 1
  num_iter = 0
  while err>tol and num_iter<max_iter:
    x0 = x_new.copy()
    for i in range(n):
      x_new[i] = (b[i] - sum([A[i][j]*x0[j] for j in range(n) if j != i]))/A[i][i]

    num_iter += 1
    err = dist(x_new , x0)

  if num_iter == max_iter:
    raise Exception("Número máximo de iterações atingido")

  return x_new, num_iter

  


In [2]:
A = [[2, 1], [0, -1]]
b = [1,2]

print(jacobi(A,b))


([1.5, -2.0], 3)


In [3]:
def gauss_seidel( A , b , max_iter= 10**6 , x = None , tol = 1.0e-5):
  '''Método de Jacobi no sistema Ax=b'''

  n = len(A)
  if (x == None):
    x0 = [0]*n
  else :
    x0=x.copy()

  err = 1
  num_iter = 0
  while err>tol and num_iter<max_iter:
    err = 0
    for i in range(n):
      y = ( b[i] - sum([A[i][j]*x0[j] for j in range(i) ])\
                  - sum([A[i][j]*x0[j] for j in range(i+1,n) ]) )\
                  /A[i][i]

      err += abs(x0[i] - y)
      x0[i]=y


    num_iter += 1

  if num_iter == max_iter:
    raise Exception("Número máximo de iterações atingido")

  return x0, num_iter


In [4]:
n=100

A = np.random.randint(low=-3,high=3,size=(n,n))
for i in range(n):
  A[i][i] = 100

b = np.random.randint(low=-10,high=10,size=n)

print (A)


print(jacobi(A,b))
print(gauss_seidel(A,b))

x = np.array(gauss_seidel(A,b)[0]).reshape(n,1)

print(f"b={b}")
print(f"Ax={A@x}")


[[100  -2   2 ...   1  -1  -3]
 [ -3 100  -1 ...   0  -1  -3]
 [  1  -3 100 ...   2   2  -2]
 ...
 [  1   1  -1 ... 100  -3  -3]
 [  2   1  -2 ...  -3 100  -1]
 [  0  -2  -3 ...  -3  -3 100]]
([-0.024881901430402937, -0.050442137820999544, -0.056887693075713085, 0.03885236240798605, 0.0511080845977883, 0.08810957330802564, 0.04975835765848962, 0.028777849403784864, -0.011454545917828714, -0.008580657514574559, 0.07396237161598433, 0.05306374524029924, 0.09198795003598587, -0.020613371169942864, 0.08669523245911366, 0.07908429277966747, -0.021712695967634366, -0.00891892327093156, 0.043858422527701287, -0.040846581657174766, -0.10209336631928899, 0.08950091693119218, -0.008901303855397275, 0.07073546634517337, 0.09399075066757004, -0.051595048491978705, 0.07379415680246947, -0.05459350041957948, 0.08191364951988929, 0.059999939670766986, -0.07937825436239061, 0.0359801793400084, 0.09174525716584249, 0.046462735344591444, -0.014686364719911941, -0.10381533784025411, 0.023703151201111425,

### Fazendo vários testes e pegando os valores em uma lista

In [18]:
import time
from tqdm import tqdm

dados_gauss_seidel=[]


for i in tqdm(range (0,121)):
    A = np.random.randint(low=-3,high=3,size=(i,i)) #cria uma matriz A de tamanho i
    b = np.random.randint(low=-10,high=10,size=i)   #cria uma matriz b
    for k in range(i):                              # Força as entradas diagonais a ser maior para poder ser diagonalmente dominante
        A[i][i] = 100

    inicio  = time.time()                           # começa o temporizador
    for n in range(10):
        gauss_seidel(A,b)[0]
    fim = time.time()
    dados_gauss_seidel.append([i, (time)])

dados_gauss_seidel = np.array(dados_gauss_seidel)




    



  0%|          | 0/121 [00:00<?, ?it/s]


TypeError: list indices must be integers or slices, not tuple